'use client'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/footer'
import Head from 'next/head'
import Transition from './TransitionEffect'
import Script from 'next/script'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>TedxVitPune2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>{children}</main>
      <Footer />
      <Script src="https://unpkg.com/blotterjs-fork@0.1.0/build/blotter.min.js" />
    </>
  )
}
