import { useState, useEffect } from 'react'
import React from 'react'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/footer'
import Head from 'next/head'
import Transition from './TransitionEffect'

export default function Layout({ children }) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);

  return (
    <>
      <Head>
        <title>TedxVitPune2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/blotterjs-fork@0.1.0/build/blotter.min.js"></script>
      </Head>
      
      <Navbar />
      {React.Children.map(children, (child) => {
        return loading ? <Loader /> : child;
      })}
      <Footer />
    </>
  )
}
